# Generated by Django 5.2.6 on 2025-09-18 12:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="id",
            field=models.CharField(
                default=main.models.generate_random_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.CharField(
                default=main.models.generate_random_id,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
