# Generated by Django 5.2.6 on 2025-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_doctor_id_alter_patient_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=23)),
                ("username", models.CharField(max_length=150)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("verified", models.BooleanField(default=False)),
                ("device_ip", models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterField(
            model_name="doctor",
            name="id",
            field=models.CharField(
                editable=False, max_length=23, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="id",
            field=models.CharField(
                editable=False, max_length=23, primary_key=True, serialize=False
            ),
        ),
    ]
