# Generated by Django 5.2.6 on 2025-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_loginrecord_alter_doctor_id_alter_patient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginrecord",
            name="occupation",
            field=models.CharField(default="Unknown", max_length=20),
        ),
    ]
